---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        imagePullPolicy: IfNotPresent
        args:
        - -log.level=debug
        - -config.file=/etc/prometheus/prometheus.yml
        - -web.listen-address=:80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      - name: watch
        image: weaveworks/watch:master-5b2a6e5
        imagePullPolicy: IfNotPresent
        args: ["-v", "-t", "-p=/etc/prometheus", "curl", "-X", "POST", "--fail", "-o", "-", "-sS", "http://localhost:80/-/reload"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
